################
### build UI ###
################

# base image
FROM node:12.13.0 as build

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY app/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@8.3.22

# add app
COPY app /app

# generate build
#CMD ng build --prod --output-path=/output/dist 
CMD ng build --output-path=/output/dist 

#Run 'sh build_angular.sh' from the root of this dir to use this docker file




